### ISSUE TITLE
Error - NullPointerException

### ISSUE THREAD

**Issue by wendypowley** [jdf/processing.py#276] opened 2017-09-15 21:10 UTC
I am teaching a class using Processing in Python mode.   Out of my 120 students, 3 of them are getting this error when trying to run any sketch in Python.    Java mode works fine.
java.lang.NullPointerException
at jycessing.Runner.runSketchBlocking(Runner.java:315)
at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:118)
at java.lang.Thread.run(Thread.java:748)

Would appreciate help if you can!

**Comment by jdf** [comment] 2017-09-16 01:20
Do those three students always use the same machines when attempting to run Processing?

Is there anything at all different about those machines?

What platform? What version of processing? What version of Python mode?

**Comment by wendypowley** [comment] 2017-09-16 20:46
Thanks for the response Jonathan!

The 3 students are using their individual laptops (one was a Surface) -- I'm afraid I don't recall if they were all windows (I'm sure two of them were windows OS but I'm not sure about the 3rd).  

They have just downloaded processing 3 from the website and used this to install Python mode.

One of the students claimed that he created another account on his machine and this solved the problem.  (I saw this mentioned in another post -- that someone was using Chinese characters in their user ids and the same error occurred).   I have asked them to try creating new accounts and I will let you know if this fixes the problem. 

Wendy

**Comment by jdf** [comment] 2017-09-17 14:26
Yes, there's an infuriating known issue with non-ASCII usernames, that I've been unable to reproduce or track down. I apologize sincerely for that. I'm going to close this, and treat it as a duplicate of #253.

**Closed by jdf** 2017-09-17 14:26 UTC
