### ISSUE TITLE
Serial library doesn't seem to work

### ISSUE THREAD

**Issue by ericksonla** [jdf/processing.py#139] opened 2015-02-27 14:59 UTC
I'm trying to use the serial library to communicate with an arduino but it doesn't look like processing.py has full support yet.  Here is the code I have:

<pre>from processing.serial import Serial

def setup():
    print Serial.list()
    portIndex = 4
    LF = 10
    print "Connecting to ", Serial.list()[portIndex]
    myPort = Serial(this, Serial.list()[portIndex], 9600)
    myPort.bufferUntil(LF)
    
def draw():
    pass
    
def serialEvent(evt):
    inString = evt.readString()
    print inString </pre>

This gives me the error: `processing.app.SketchException: java.lang.UnsatisfiedLinkError: jssc.SerialNativeInterface.openPort(Ljava/lang/String;Z)J`

Some googling suggests that is a problem where the processing code isn't converting it to Java correctly. Any suggestions? Do I have a bug or does some separate support for the serial library need to be added?

**Comment by kazimuth** [comment] 2015-02-27 16:57
Python mode doesn't actually convert python to Java code, so that isn't the problem. It looks like Processing is having trouble finding the serial native library - have you done any shenanigans with your processing install?

**Comment by ericksonla** [comment] 2015-02-27 17:22
No shenanigans with the serial native library. I can run the [simple example](https://processing.org/reference/libraries/serial/Serial.html) in Java mode just fine.

**Comment by kazimuth** [comment] 2015-02-27 20:01
Oh, the problem is that you're using normal python import statements.
For python mode imports, you should use `add_library()`:
```python
add_library('serial') # I think this is the right name

def setup():
    print Serial.list()
    portIndex = 4
    LF = 10
    print "Connecting to ", Serial.list()[portIndex]
    myPort = Serial(this, Serial.list()[portIndex], 9600)
    myPort.bufferUntil(LF)
    
def draw():
    pass
    
def serialEvent(evt):
    inString = evt.readString()
    print inString
```

**Comment by koniho** [comment] 2015-11-18 22:26
I've created a wrapper around processing.serial.Serial that is (mostly) API compatible with PySerial's Serial class. Currently, if my `serial.py` module exists in the sketch folder any modules that `import serial` should pick up the wrapper module.

I'm new to processing and was wondering what would be a good place for that code. Would this be a part of `processing.py` or should this be in a processing library?

**Comment by jdf** [comment] 2015-11-18 22:37
@kazimuth's https://github.com/jdf/processing.py/issues/139#issuecomment-76461862 comment was correct. Closing, but reopen if `add_library` doesn't work as expected.

**Closed by jdf** 2015-11-18 22:37 UTC

**Comment by tildebyte** [comment] 2015-11-19 15:59
@koniho You'll probably want to open a separate issue to discuss that.
