### ISSUE TITLE
Find in reference in Python mode

### ISSUE THREAD

**Issue by mmammana** [jdf/processing.py#228] opened 2017-01-04 22:59 UTC
Hi, I hope you are all fine and had happy holidays!
I cannot make "find in reference" work for Python Mode. I am using Processing 3 (3.2.3) and downloaded the last version of py mode for processing 3 (yesterday), but when I right-click on some function or whatever, "find in reference" gives a missing url error. I've looked into Processing.org forum, and also here, and only found a post in the bugs section, in 2015, (https://github.com/jdf/Processing.py-Bugs/issues/126) asking for the same problem, but with no solution released. Any help? 
Thanks, 
Marcelo

**Comment by Karim-92** [comment] 2017-03-08 16:05
The problem is that it's trying to navigate to a folder that doesn't exist in Python mode. Apparently the reference folder isn't downloaded with the python mode. However it does reside in the Processing 3.x folder itself under modes-->Java-->reference.
A possible fix for this would be to copy that reference folder and paste it in the location which the "find by reference" function tries to access. On windows that location is C:\Users\~yourUsernameHere\Documents\Processing\modes\PythonMode
This fixes the problem.

**Closed** 2017-09-03 01:14 UTC
