### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by yzaki** [jdf/processing.py#221] opened 2016-11-17 06:41 UTC
I have installed processing 3.2.3 and downloaded the python mode. If I try to run my code I get the following error:

java.lang.NullPointerException
at jycessing.Runner.runSketchBlocking(Runner.java:303)
at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:114)
at java.lang.Thread.run(Unknown Source)

I have checked processing with Java and it works. So it must be an issue with the python mode.
Any ideas? I am using windows 10

**Comment by yzaki** [comment] 2016-11-24 18:31
We have figured what the problem was. My student had her windows user account name in Chinese. By creating a new account with an English name everything worked smoothly.

**Comment by jdf** [comment] 2016-12-13 15:48
Thanks very much, @yzaki. I'd like to address the underlying cause. Could I trouble you to follow up with the language and locale settings of your student's laptop?

**Comment by jdf** [comment] 2017-07-08 13:10
Duplicate of #253

**Closed by jdf** 2017-07-08 13:10 UTC
