### ISSUE TITLE
Broken example: Morph

### ISSUE THREAD

**Issue by berinhard** [jdf/processing.py#335] opened 2019-01-11 18:19 UTC
The example code `Morph` is raising an error. It's located under `Topics > Motion`.

The exception I'm being raised at the line 76 and its description is:

```
processing.app.SketchException: TypeError: 'processing.core.PVector' object is unsubscriptable
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:240)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

It seems to be the same exception I've described in #334.

**Comment by jdf** [comment] 2019-01-11 19:16
Duplicate of #334

**Closed by jdf** 2019-01-11 19:16 UTC
